export default {
  // user-role
  RECEIVE_FETCH_USERS: 'RECEIVE_FETCH_USERS',
  REQUEST_FETCH_USERS: 'REQUEST_FETCH_USERS',

  CLICK_USER_ITEM: 'CLICK_USER_ITEM',

  REQUEST_UPDATE_USER_ROLES: 'REQUEST_UPDATE_USER_ROLES',
  RECEIVE_UPDATE_USER_ROLES: 'RECEIVE_UPDATE_USER_ROLES',

  REQUEST_FETCH_ROLES: 'REQUEST_FETCH_ROLES',
  RECEIVE_FETCH_ROLES: 'RECEIVE_FETCH_ROLES',


  // user-detail
  REQUEST_USER_DETAIL: 'REQUEST_USER_DETAIL',
  RECEIVE_USER_DETAIL: 'RECEIVE_USER_DETAIL',

  REQUEST_ADD_USER: 'REQUEST_ADD_USER',
  RECEIVE_ADD_USER: 'RECEIVE_ADD_USER',

  REQUEST_UPDATE_USER: 'REQUEST_UPDATE_USER',
  RECEIVE_UPDATE_USER: 'RECEIVE_UPDATE_USER',

  REQUEST_DELETE_USER: 'REQUEST_DELETE_USER',
  RECEIVE_DELETE_USER: 'RECEIVE_DELETE_USER',


  // role-detail
  REQUEST_ROLE_DETAIL: 'REQUEST_ROLE_DETAIL',
  RECEIVE_ROLE_DETAIL: 'RECEIVE_ROLE_DETAIL',

  REQUEST_ADD_ROLE: 'REQUEST_ADD_ROLE',
  RECEIVE_ADD_ROLE: 'RECEIVE_ADD_ROLE',

  REQUEST_UPDATE_ROLE: 'REQUEST_UPDATE_ROLE',
  RECEIVE_UPDATE_ROLE: 'RECEIVE_UPDATE_ROLE'
};
